accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('', include('accounts.urls')),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('signout/', views.signout_view, name='signout'),
]

api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('v1/',views.index,name='index'),
]

my_app/urls.py
from django.urls import path
from . import views

app_name='my_app'

urlpatterns=[
    path('',views.app_home,name='app_home'),
    path('blog/',views.blog_home,name='blog_home'),
    path('blog/<int:post_id>/',views.blog_post,name='blog_post'),
    path('blog/category/<str:category_name>/',views.blog_home,name='blog_category'),
    path('blog/author/<str:author_name>/',views.blog_home,name='blog_author'),
    path('blog/search/',views.blog_home,name='blog_search'),
    path('contact/',views.contact,name='contact'),
]

my_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('my_app/', include('my_app.urls')),
    path('shop/', include('shop.urls')),
    path('milad/',LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('reset', PasswordResetView.as_view(template_name='accounts/password_reset.html'),name='reset'),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_app/models.py
from django.db import models

class Comments(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=255)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Authors(models.Model):
    username = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=30)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField()
    def __str__(self) -> str:
        return self.first_name + ' ' + self.last_name


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    images = models.ImageField(upload_to='images/')
    counter_view = models.IntegerField(default=0)
    author = models.ForeignKey(Authors, on_delete=models.SET_NULL, null=True)
    category = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)
    comments = models.ManyToManyField(Comments)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created_at',)
    
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=30)
    message = models.CharField(max_length=1200)
        
    def __str__(self):
        return self.subject

my_app/forms.py
from django import forms
from my_app.models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

my_app/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from my_app.forms import ContactForm
from my_app.models import Authors, Category, Comments, Post
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.


def app_home(request):
    return render(request, 'my_app/index.html')


def blog_home(request, **kwargs):
    posts = Post.objects.filter(is_active=True)
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if kwargs.get('category_name'):
        posts = posts.filter(category__name=kwargs['category_name'])
    if kwargs.get('author_name'):
        posts = posts.filter(author__username=kwargs['author_name'])
    if querry := request.GET.get('search'):
        posts = posts.filter(content__icontains=querry)
    return render(request, 'my_app/blog_home.html', {'posts': posts})

@login_required(login_url='/accounts/login/')
def blog_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, is_active=True)
    post.counter_view += 1
    post.save()

    return render(request, 'my_app/blog_post.html', {'post': post})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been sent!')
            return render(request, 'my_app/contact.html')
        else:
            messages.error(request, 'Your message has not been sent!')
            return render(request, 'my_app/blog_home.html')
    return render(request, 'my_app/contact.html')

my_app/templates/my_app/blog_home.html
{% load static %}
{% load blog_tags %}
{% include 'my_app/header.html' %}
		<body>	
			<header id="header">
				<div class="header-top">
					<div class="container">
			  		<div class="row align-items-center">
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-left">
			  				<ul>
								{% if request.user.is_authenticated %}

								<li><a href="{% url 'accounts:signout' %}">Logout</a></li>
								<li><a href="#">You are {{ request.user.username }}</a></li>
								
								
	{% else %}
								<li><a href="{% url 'accounts:login' %}">Login</a></li>
								<li><a href="{% url 'accounts:signup' %}">Register</a></li>
	{% endif %}
			  				</ul>			
			  			</div>
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-right">
							<div class="header-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
			  			</div>
			  		</div>			  					
					</div>
				</div>
{% include 'my_app/includes/main_menu_tag.html' %}
			</header><!-- #header -->

			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'my_app/img/blog/cat-widget1.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'my_app/img/blog/cat-widget2.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'my_app/img/blog/cat-widget3.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							{% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for cat in post.category.all %}
										<li><a href="{% url 'my_app:blog_category' category_name=cat %}">{{ cat }}{% if not forloop.last %}, {% endif %}</a></li>
										{% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'my_app:blog_author' author_name=post.author.username %}">{{ post.author }}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.created_at | date:'Y m d' }}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counter_view }} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{ post.images.url }}" alt="">
									</div>
									<a class="posts-title" href="{% url 'my_app:blog_post' post_id=post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										{{post.content | snippet}}
									</p>
									<a href="{% url 'my_app:blog_post' post_id=post.id %}" class="primary-btn">View More</a>
								</div>
							</div>	
							{% endfor %}
													
		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
									{% if posts.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{posts.previous_page_number}}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}


									{% for i in posts.paginator.page_range %}
									{% if posts.number == i %}
									<li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
									{% else %}
									<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
									{% endif %}
									{% endfor %}


									{% if posts.has_next %}
		                            <li class="page-item">
										<a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}

		                        </ul>
		                    </nav>




						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								<div class="single-sidebar-widget search-widget">
									<form class="search-form" action="{% url 'my_app:blog_search' %}" method="get">
			                            <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
			                            <button type="submit"><i class="fa fa-search"></i></button>
			                        </form>
								</div>
								<div class="single-sidebar-widget user-info-widget">
									<img src="{% static 'my_app/img/blog/user-info.png' %}" alt="">
									<a href="#"><h4>Charlie Barber</h4></a>
									<p>
										Senior blog writer
									</p>
									<ul class="social-links">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-github"></i></a></li>
										<li><a href="#"><i class="fa fa-behance"></i></a></li>
									</ul>
									<p>
										Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
									</p>
								</div>
								{% latest_posts %}
								<div class="single-sidebar-widget ads-widget">
									<a href="#"><img class="img-fluid" src="{% static 'my_app/img/blog/ads-banner.jpg' %}" alt=""></a>
								</div>
{% category_list %}	
								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>	
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>								
								</div>
								<div class="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Architecture</a></li>
										<li><a href="#">Fashion</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Technology</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Art</a></li>
										<li><a href="#">Adventure</a></li>
										<li><a href="#">Food</a></li>
										<li><a href="#">Lifestyle</a></li>
										<li><a href="#">Adventure</a></li>
									</ul>
								</div>								
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			
			<!-- start footer Area -->		
			{% include 'my_app/footer.html' %}
		</body>
	</html>

my_app/templates/my_app/blog_post.html
{% load static %}
{% include 'my_app/header.html' %}

<body>
	<header id="header">
		<div class="header-top">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6 col-sm-6 col-6 header-top-left">
						<ul> {% if request.user.is_authenticated %}
							<li><a href="#">Logout</a></li>
							<li><a href="#">You are {{ request.user.username }}</a></li> {% else %}
							<li><a href="#">Login</a></li>
							<li><a href="#">Register</a></li> {% endif %} </ul>
					</div>
					<div class="col-lg-6 col-sm-6 col-6 header-top-right">
						<div class="header-social"> <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-behance"></i></a> </div>
					</div>
				</div>
			</div>
		</div> {% include 'my_app/includes/main_menu_tag.html' %} </header>
	<!-- #header -->
	<!-- start banner Area -->
	<section class="relative about-banner">
		<div class="overlay overlay-bg"></div>
		<div class="container">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content col-lg-12">
					<h1 class="text-white">{{ post.title }}</h1>
					<p class="text-white link-nav"> <a href="{% url 'my_app:app_home' %}">Home</a> <span class="lnr lnr-arrow-right"></span
                     ><a href="{% url 'my_app:blog_home' %}">Blog</a>
                  <span class="lnr lnr-arrow-right"></span> {{ post.title }} </p>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->
	<!-- Start post-content Area -->
	<section class="post-content-area single-post-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 posts-list">
					<div class="single-post row">
						<div class="col-lg-12">
							<div class="feature-img"> <img class="img-fluid" src="{{ post.images.url }}" alt="" /> </div>
						</div>
						<div class="col-lg-3 col-md-3 meta-details">
							<ul class="tags"> {% for cat in post.category.all %}
								<li> <a href="#">{{ cat }}
                           {% if not forloop.last %},{% endif %}
                           </a> </li> {% endfor %} </ul>
							<div class="user-details row">
								<p class="user-name col-lg-12 col-md-12 col-6"> <a href="#">{{ post.author }}</a> <span class="lnr lnr-user"></span> </p>
								<p class="date col-lg-12 col-md-12 col-6"> <a href="#">{{ post.created_at | date:"M d, Y" }}</a> <span class="lnr lnr-calendar-full"></span> </p>
								<p class="view col-lg-12 col-md-12 col-6"> <a href="#">{{ post.counter_view }} Views</a> <span class="lnr lnr-eye"></span> </p>
								<p class="comments col-lg-12 col-md-12 col-6"> <a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span> </p>
								<ul class="social-links col-lg-12 col-md-12 col-6">
									<li> <a href="#"><i class="fa fa-facebook"></i></a> </li>
									<li> <a href="#"><i class="fa fa-twitter"></i></a> </li>
									<li> <a href="#"><i class="fa fa-github"></i></a> </li>
									<li> <a href="#"><i class="fa fa-behance"></i></a> </li>
								</ul>
							</div>
						</div>
						<div class="col-lg-9 col-md-9">
							<h3 class="mt-20 mb-20">
                        {{ post.title }}
                     </h3>
							<p class="excert"> {{ post.content }} </p>
						</div>
					</div>
					<div class="navigation-area">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center"> {% if post.get_previous_by_created_at %}
								<div class="thumb">
									<a href="{% url 'my_app:blog_post' post_id=post.get_previous_by_created_at.id %}"> <img class="img-fluid" width=100px height=100px src="{{ post.get_previous_by_created_at.images.url }}" alt="" /> </a>
								</div>
								<div class="arrow"> <a href="{% url 'my_app:blog_post' post_id=post.get_previous_by_created_at.id %}"><span class="lnr text-white lnr-arrow-left"></span
                              ></a> </div>
								<div class="detials">
									<p> Prev Post </p>
									<a href="{% url 'my_app:blog_post' post_id=post.get_previous_by_created_at.id %}">
										<h4>
                                 {{post.get_previous_by_created_at.title}}
                              </h4> </a>
								</div> {% endif %} </div>
							<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center"> {% if post.get_next_by_created_at %}
								<div class="detials">
									<p> Next Post </p>
									<a href="{% url 'my_app:blog_post' post_id=post.get_next_by_created_at.id %}">
										<h4>
                                 {{post.get_next_by_created_at.title}}
                              </h4> </a>
								</div>
								<div class="arrow"> <a href="#"><span class="lnr text-white lnr-arrow-right"></span
                              ></a> </div>
								<div class="thumb">
									<a href="{% url 'my_app:blog_post' post_id=post.get_next_by_created_at.id %}"> <img class="img-fluid" src="{% static '{{post.get_next_by_created_at.images.url}}' %}" alt="" /> </a>
								</div> {% endif %} </div>
						</div>
					</div>
					<div class="comments-area">
						<h4>
                     05 Comments
                  </h4> {% for comment in post.comments.all %}
						<div class="comment-list">
							<div class="single-comment justify-content-between d-flex">
								<div class="user justify-content-between d-flex">
									<div class="thumb"> <img src="{% static 'my_app/img/blog/c1.jpg' %}" alt="" /> </div>
									<div class="desc">
										<h5>
                                 <a href="#">{{ comment.name }}</a>
                              </h5>
										<p class="date"> {{ comment.created_at | date:'Y m d H m' }} </p>
										<p class="comment"> {{ comment.content }} </p>
									</div>
								</div>
								<div class="reply-btn"> <a href="" class="btn-reply text-uppercase">reply</a> </div>
							</div>
						</div> {% endfor %} </div>
					<div class="comment-form">
						<h4>
                     Leave a Comment
                  </h4>
						<form>
							<div class="form-group form-inline">
								<div class="form-group col-lg-6 col-md-12 name">
									<input type="text" class="form-control" id="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'" /> </div>
								<div class="form-group col-lg-6 col-md-12 email">
									<input type="email" class="form-control" id="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" /> </div>
							</div>
							<div class="form-group">
								<input type="text" class="form-control" id="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'" /> </div>
							<div class="form-group">
								<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
							</div> <a href="#" class="primary-btn text-uppercase">Post Comment</a> </form>
					</div>
				</div>
				<div class="col-lg-4 sidebar-widgets">
					<div class="widget-wrap">
						<div class="single-sidebar-widget search-widget">
							<form class="search-form" action="#">
								<input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" />
								<button type="submit"> <i class="fa fa-search"></i> </button>
							</form>
						</div>
						<div class="single-sidebar-widget user-info-widget"> <img src="{% static 'my_app/img/blog/user-info.png' %}" alt="" />
							<a href="#">
								<h4>
                           Charlie Barber
                        </h4> </a>
							<p> Senior blog writer </p>
							<ul class="social-links">
								<li> <a href="#"><i class="fa fa-facebook"></i></a> </li>
								<li> <a href="#"><i class="fa fa-twitter"></i></a> </li>
								<li> <a href="#"><i class="fa fa-github"></i></a> </li>
								<li> <a href="#"><i class="fa fa-behance"></i></a> </li>
							</ul>
							<p> Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors. </p>
						</div>
						<div class="single-sidebar-widget popular-post-widget">
							<h4 class="popular-title">
                        Popular Posts
                     </h4>
							<div class="popular-post-list">
								<div class="single-post-list d-flex flex-row align-items-center">
									<div class="thumb"> <img class="img-fluid" src="{% static 'my_app/img/blog/pp1.jpg' %}" alt="" /> </div>
									<div class="details">
										<a href="blog-single.html">
											<h6>
                                    Space The Final Frontier
                                 </h6> </a>
										<p> 02 Hours ago </p>
									</div>
								</div>
								<div class="single-post-list d-flex flex-row align-items-center">
									<div class="thumb"> <img class="img-fluid" src="{% static 'my_app/img/blog/pp2.jpg' %}" alt="" /> </div>
									<div class="details">
										<a href="blog-single.html">
											<h6>
                                    The Amazing Hubble
                                 </h6> </a>
										<p> 02 Hours ago
                                             </p>
									</div>
								</div>
								<div class="single-post-list d-flex flex-row align-items-center">
									<div class="thumb"> <img class="img-fluid" src="{% static 'my_app/img/blog/pp3.jpg' %}" alt="" /> </div>
									<div class="details">
										<a href="blog-single.html">
											<h6>
                                    Astronomy Or Astrology
                                 </h6> </a>
										<p> 02 Hours ago </p>
									</div>
								</div>
								<div class="single-post-list d-flex flex-row align-items-center">
									<div class="thumb"> <img class="img-fluid" src="{% static 'my_app/img/blog/pp4.jpg' %}" alt="" /> </div>
									<div class="details">
										<a href="blog-single.html">
											<h6>
                                    Asteroids telescope
                                 </h6> </a>
										<p> 02 Hours ago </p>
									</div>
								</div>
							</div>
						</div>
						<div class="single-sidebar-widget ads-widget">
							<a href="#"> <img class="img-fluid" src="{% static 'my_app/img/blog/ads-banner.jpg' %}" alt="" /> </a>
						</div>
						<div class="single-sidebar-widget post-category-widget">
							<h4 class="category-title">
                        Post Catgories
                     </h4>
							<ul class="cat-list">
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p> Technology </p>
										<p> 37 </p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p> Lifestyle </p>
										<p> 24 </p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p> Fashion </p>
										<p> 59 </p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p> Art </p>
										<p> 29 </p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p> Food </p>
										<p> 15 </p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p> Architecture </p>
										<p> 09 </p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p> Adventure </p>
										<p> 44 </p>
									</a>
								</li>
							</ul>
						</div>
						<div class="single-sidebar-widget newsletter-widget">
							<h4 class="newsletter-title">
                        Newsletter
                     </h4>
							<p> Here, I focus on a range of items and features that we use in life without giving them a second thought. </p>
							<div class="form-group d-flex flex-row">
								<div class="col-autos">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text"> <i class="fa fa-envelope" aria-hidden="true"></i> </div>
										</div>
										<input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" /> </div>
								</div> <a href="#" class="bbtns">Subcribe</a> </div>
							<p class="text-bottom"> You can unsubscribe at any time </p>
						</div>
						<div class="single-sidebar-widget tag-cloud-widget">
							<h4 class="tagcloud-title">
                        Tag Clouds
                     </h4>
							<ul> {% for tag in post.tags.all %}
								<li> <a href="#">{{ tag }}</a> </li> {% endfor %} </ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End post-content Area -->
	<!-- start footer Area -->
    {% include 'my_app/footer.html' %} 
</body>

</html>