api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('v1/',views.index,name='index'),
]

my_app/urls.py
from django.urls import path
from . import views

app_name='my_app'

urlpatterns=[
    path('',views.app_home,name='app_home'),
    path('blog/',views.blog_home,name='blog_home'),
    path('blog/<int:post_id>/',views.blog_post,name='blog_post'),
    path('blog/category/<str:category_name>/',views.blog_home,name='blog_category'),
    path('blog/author/<str:author_name>/',views.blog_home,name='blog_author'),
    path('blog/search/',views.blog_home,name='blog_search'),
    path('contact/',views.contact,name='contact'),
]

my_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('my_app/', include('my_app.urls')),
    path('shop/', include('shop.urls')),
    path('milad/',LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('reset', PasswordResetView.as_view(template_name='accounts/password_reset.html'),name='reset'),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_app/models.py
from django.db import models

class Comments(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=255)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Authors(models.Model):
    username = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=30)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField()
    def __str__(self) -> str:
        return self.first_name + ' ' + self.last_name


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    images = models.ImageField(upload_to='images/')
    counter_view = models.IntegerField(default=0)
    author = models.ForeignKey(Authors, on_delete=models.SET_NULL, null=True)
    category = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)
    comments = models.ManyToManyField(Comments)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created_at',)
    
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=30)
    message = models.CharField(max_length=1200)
        
    def __str__(self):
        return self.subject

my_app/forms.py
from django import forms
from my_app.models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

my_app/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from my_app.forms import ContactForm
from my_app.models import Authors, Category, Comments, Post
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.


def app_home(request):
    return render(request, 'my_app/index.html')


def blog_home(request, **kwargs):
    posts = Post.objects.filter(is_active=True)
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if kwargs.get('category_name'):
        posts = posts.filter(category__name=kwargs['category_name'])
    if kwargs.get('author_name'):
        posts = posts.filter(author__username=kwargs['author_name'])
    if querry := request.GET.get('search'):
        posts = posts.filter(content__icontains=querry)
    return render(request, 'my_app/blog_home.html', {'posts': posts})

@login_required(login_url='/accounts/login/')
def blog_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, is_active=True)
    post.counter_view += 1
    post.save()

    return render(request, 'my_app/blog_post.html', {'post': post})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been sent!')
            return render(request, 'my_app/contact.html')
        else:
            messages.error(request, 'Your message has not been sent!')
            return render(request, 'my_app/blog_home.html')
    return render(request, 'my_app/contact.html')

my_app/templates/my_app/includes/category_count_sidebar.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name,value in categories.items %}
        {% if value > 0 %}
        <li>
            <a href="{% url 'my_app:blog_category' category_name=name %}" class="d-flex justify-content-between">
                <p>{{name}}</p>
                <p>{{value}}</p>
            </a>
        </li>	
        {% endif %}
        {% endfor %}
														
    </ul>
</div>

my_app/templates/my_app/includes/latest_posts_tag.html
{% load static %}


<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    {% for post in posts %}
    <div class="popular-post-list">
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{post.images.url}}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'my_app:blog_post' post_id=post.id %}"><h6>{{post.title}}</h6></a>
                <p>{{post.created_at}}</p>
            </div>
        </div>														
    </div>
    {% endfor %}
</div>

my_app/templates/my_app/includes/main_menu_tag.html
{% load static %}
<div class="container main-menu">
    <div class="row align-items-center justify-content-between d-flex">
      <div id="logo">
        <a href="index.html"><img src="{% static 'my_app/img/logo.png' %}" alt="" title="" /></a>
      </div>
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li><a href="{% url 'my_app:app_home' %}">Home</a></li>
          <li><a href="about.html">About</a></li>
          <li class="menu-has-children"><a href="{% url 'my_app:blog_home' %}">Blog</a></li>					          					          		          
          <li><a href="{% url 'my_app:contact' %}">Contact</a></li>
        </ul>
      </nav><!-- #nav-menu-container -->					      		  
    </div>
</div>