api/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('v1/',views.index,name='index'),
]

my_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('my_app/', include('my_app.urls')),
    path('shop/', include('shop.urls')),
    path('milad/',LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('reset', PasswordResetView.as_view(template_name='accounts/password_reset.html'),name='reset'),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
    path('', views.shop_home, name='shop_home'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:pk>/', views.edit_product, name='edit_product'),
]

shop/models.py
from email.policy import default
from django.db import models

# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.BigIntegerField()
    image = models.ImageField(upload_to='shop/', default='shop/default.png')
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name


    

shop/forms.py
from .models import Product
from django import forms

class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

shop/views.py
from django.shortcuts import render, get_object_or_404

from shop.forms import AddProductForm
from .models import Product

# Create your views here.


def shop_home(request):
    products = Product.objects.all()
    return render(request, 'shop/shop_home.html', {'products': products})


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'shop/product_detail.html', {'product': product})


def add_product(request):
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'shop/add_product.html', {'form': form, "msg": "Product added successfully"})
        else:
            return render(request, 'shop/add_product.html', {'form': form, 'msg': "Product not added"})
    form = AddProductForm()
    return render(request, 'shop/add_product.html', {'form': form})


def edit_product(request, pk):
    if request.method == 'POST':
        instance=get_object_or_404(Product,pk=pk)
        form = AddProductForm(request.POST,instance=instance)
        if form.is_valid():
            form.save()
            return render(request, 'shop/edit_product.html', {'form': form, "msg": "Product updated successfully"})
    product = get_object_or_404(Product, pk=pk)
    form = AddProductForm(instance=product)
    return render(request, 'shop/edit_product.html', {'form': form, 'product': product})

shop/templates/shop/add_product.html
{% extends 'shop/base.html' %}
{% block content %}
{{msg}}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- <input type="text" name="name" placeholder="Name">
    <input type="text" name="description" placeholder="Description">
    <input type="text" name="price" placeholder="Price">
    <input type="file" name="image" accept="image/*">
    <input type="checkbox" name="available" value="available"> -->
    {{form}}
    <input type="submit" name="submit" value="Submit">
</form>

<ul>
{{form.errors}}
</ul>

{% endblock %}

shop/templates/shop/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <title>Shop</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
{% url 'test' %}
{% milad %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:shop_home' %}">Shop</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:add_product' %}">add</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>

shop/templates/shop/edit_product.html
{% extends 'shop/base.html' %}
{% block content %}
{{msg}}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- <input type="text" name="name" placeholder="Name">
    <input type="text" name="description" placeholder="Description">
    <input type="text" name="price" placeholder="Price">
    <input type="file" name="image" accept="image/*">
    <input type="checkbox" name="available" value="available"> -->
    {{form}}
    <input type="submit" name="submit" value="Submit">
</form>
{{msg}}
{% endblock %}

shop/templates/shop/product_detail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{product.title}}</title>
</head>
<body>
    <p>{{ product.title }}</p>
    <p>{{ product.description }}</p>
    <p>{{ product.price }}</p>
    <p><img src="{{product.image.url}}" alt=""></p>
    <a href="{% url 'shop:edit_product' pk=product.id %}">Edit Product</a>
</body>
</html>

shop/templates/shop/shop_home.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="card-deck">
    {% for product in products %}
    <div class="card">
      <img class="" width="150px" src="{{product.image.url}}" alt="Card image cap">
      <div class="card-body">
        <a href="{% url 'shop:product_detail' pk=product.id %}">{{product.title}}</a>
        <a href="{% url 'shop:product_detail' pk=product.id %}">{{product.description}}</a>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}